In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
folder = os.path.join(os.getcwd(), "data")
file = os.path.join(folder, "metal_bands_2017.csv")
data = pd.read_csv(file, encoding="unicode_escape")
data = data.drop("Unnamed: 0", axis=1)
data = data.drop("split",axis = 1)

In [119]:
for row in data.itertuples():

  list_genres = row[5].split(",")
  band_name = row[1].split(",")
  country_name = row[4].split(",")
  genres = "_".join(list_genres)
  band = "_".join(band_name)
  country = "_".join(country_name)
  data.loc[row[0],"style"] = genres
  data.loc[row[0],"band_name"] = band
  data.loc[row[0],"origin"] = country

In [121]:
data = data.set_index("band_name")
data.to_csv("data/metal_bands_2017_updated.csv")

In [36]:
for row in data.itertuples():
  try:
    int(row[1])
  except:
    print(row[1])

In [91]:
data[data["style"] == "Heavy"]

                  fans  formed               origin  style
band_name
Dio               1023    1982                  USA  Heavy
MotÃ¶rhead         875    1975  United Kingdom, USA  Heavy
Ozzy Osbourne      750    1979  United Kingdom, USA  Heavy
King Diamond       641    1985         Denmark, USA  Heavy
Accept             601    1968              Germany  Heavy
...                ...     ...                  ...    ...
Valpurgis Night      1    2008       United Kingdom  Heavy
Vitacit              1    1972       Czech Republic  Heavy
Witchcurse           1    2005               Greece  Heavy
9.7 Richter          0    2006              Romania  Heavy
Algy Ward's Tank     0    2007       United Kingdom  Heavy

[180 rows x 4 columns]

In [89]:
data

,fans,formed,origin,style
band_name,,,,
Iron Maiden,4195,1975,United Kingdom,New wave of british heavy-Heavy
Opeth,4147,1990,Sweden,Extreme progressive-Progressive rock-Progressive
Metallica,3712,1981,USA,Heavy-Bay area thrash
Megadeth,3105,1983,USA,Thrash-Heavy-Hard rock
Amon Amarth,3054,1988,Sweden,Melodic death
...,...,...,...,...
Atara,0,2006,France,Black-Grindcore
Avicularia,0,2003,Croatia,Avantgarde death
Awake,0,2006,United Kingdom,Heavy-Progressive
Axatak,0,1983,Australia,Hard rock-Heavy
Axis Of Despair,0,2014,Sweden,Grindcore